import type { AisDisruptionEvent, AisDensityZone } from '@/types/ais';

// Sample AIS density zones (high traffic areas)
export const MOCK_AIS_DENSITY: AisDensityZone[] = [
  { id: 'malacca-1', name: 'Malacca Strait - Singapore', lat: 1.26, lon: 103.84, intensity: 0.95, deltaPct: 5, shipsPerDay: 450, note: 'Busiest strait, 80k+ vessels/year' },
  { id: 'suez-1', name: 'Suez Canal - Port Said', lat: 31.26, lon: 32.30, intensity: 0.88, deltaPct: -2, shipsPerDay: 120, note: '12% of world trade' },
  { id: 'suez-2', name: 'Suez Canal - Suez Port', lat: 29.97, lon: 32.55, intensity: 0.85, deltaPct: 0, shipsPerDay: 115, note: 'Southern terminus' },
  { id: 'hormuz-1', name: 'Strait of Hormuz', lat: 26.5, lon: 56.5, intensity: 0.92, deltaPct: 8, shipsPerDay: 280, note: '21M bpd oil transit' },
  { id: 'panama-1', name: 'Panama Canal', lat: 9.1, lon: -79.7, intensity: 0.78, deltaPct: 12, shipsPerDay: 38, note: '14k transits/year' },
  { id: 'gibraltar-1', name: 'Strait of Gibraltar', lat: 35.9, lon: -5.6, intensity: 0.75, deltaPct: 3, shipsPerDay: 300, note: 'Mediterranean gateway' },
  { id: 'dover-1', name: 'Dover Strait', lat: 51.0, lon: 1.5, intensity: 0.82, deltaPct: -1, shipsPerDay: 400, note: 'World busiest shipping lane' },
  { id: 'bab-el-mandeb-1', name: 'Bab el-Mandeb', lat: 12.5, lon: 43.3, intensity: 0.65, deltaPct: -25, shipsPerDay: 180, note: 'Red Sea crisis impact' },
  { id: 'shanghai-1', name: 'Shanghai Approaches', lat: 31.0, lon: 122.5, intensity: 0.90, deltaPct: 15, shipsPerDay: 380, note: 'World busiest container port' },
  { id: 'rotterdam-1', name: 'Rotterdam Approaches', lat: 52.0, lon: 3.8, intensity: 0.72, deltaPct: 4, shipsPerDay: 200, note: 'Europe largest port' },
  { id: 'cape-1', name: 'Cape of Good Hope', lat: -34.36, lon: 18.49, intensity: 0.55, deltaPct: 45, shipsPerDay: 90, note: 'Suez bypass traffic surge' },
  { id: 'bosphorus-1', name: 'Bosphorus Strait', lat: 41.1, lon: 29.0, intensity: 0.68, deltaPct: 2, shipsPerDay: 150, note: 'Black Sea access' },
  { id: 'taiwan-1', name: 'Taiwan Strait', lat: 24.0, lon: 119.5, intensity: 0.80, deltaPct: 8, shipsPerDay: 250, note: 'Critical shipping lane' },
  { id: 'korea-1', name: 'Korea Strait', lat: 34.0, lon: 129.0, intensity: 0.70, deltaPct: 5, shipsPerDay: 180, note: 'Japan-Korea trade' },
  { id: 'bosporus-1', name: 'Kerch Strait', lat: 45.3, lon: 36.6, intensity: 0.45, deltaPct: -30, shipsPerDay: 40, note: 'Russia-Ukraine conflict' },
];

// Sample AIS disruption events
export const MOCK_AIS_DISRUPTIONS: AisDisruptionEvent[] = [
  {
    id: 'gap-red-sea-1',
    name: 'Red Sea AIS Gap Cluster',
    type: 'gap_spike',
    lat: 15.0,
    lon: 42.0,
    severity: 'high',
    changePct: 340,
    windowHours: 24,
    darkShips: 45,
    vesselCount: 120,
    region: 'Red Sea',
    description: 'Significant AIS signal gaps detected. Vessels going dark near Houthi activity zones.',
  },
  {
    id: 'congestion-suez-1',
    name: 'Suez Canal Congestion',
    type: 'chokepoint_congestion',
    lat: 30.5,
    lon: 32.3,
    severity: 'elevated',
    changePct: 25,
    windowHours: 12,
    vesselCount: 85,
    region: 'Suez Canal',
    description: 'Above-normal queue forming at Great Bitter Lake. Delay: 6-8 hours.',
  },
  {
    id: 'gap-black-sea-1',
    name: 'Black Sea Spoofing Activity',
    type: 'gap_spike',
    lat: 44.5,
    lon: 32.0,
    severity: 'elevated',
    changePct: 180,
    windowHours: 48,
    darkShips: 12,
    vesselCount: 45,
    region: 'Black Sea',
    description: 'GPS/AIS spoofing detected near Crimea. Multiple vessels showing false positions.',
  },
  {
    id: 'congestion-panama-1',
    name: 'Panama Canal Low Water Delay',
    type: 'chokepoint_congestion',
    lat: 9.1,
    lon: -79.7,
    severity: 'high',
    changePct: 65,
    windowHours: 72,
    vesselCount: 62,
    region: 'Panama Canal',
    description: 'Draft restrictions due to low water. Transit delays up to 10 days.',
  },
  {
    id: 'gap-south-china-sea-1',
    name: 'SCS AIS Interference',
    type: 'gap_spike',
    lat: 15.0,
    lon: 115.0,
    severity: 'low',
    changePct: 45,
    windowHours: 6,
    darkShips: 8,
    vesselCount: 200,
    region: 'South China Sea',
    description: 'Intermittent AIS jamming reported near disputed territories.',
  },
  {
    id: 'congestion-la-1',
    name: 'LA/LB Port Congestion',
    type: 'chokepoint_congestion',
    lat: 33.7,
    lon: -118.2,
    severity: 'elevated',
    changePct: 30,
    windowHours: 36,
    vesselCount: 28,
    region: 'Los Angeles',
    description: 'Container backup at anchorage. Average wait: 3-4 days.',
  },
  {
    id: 'gap-persian-gulf-1',
    name: 'Gulf GPS Spoofing',
    type: 'gap_spike',
    lat: 26.5,
    lon: 52.0,
    severity: 'high',
    changePct: 290,
    windowHours: 18,
    darkShips: 22,
    vesselCount: 95,
    region: 'Persian Gulf',
    description: 'Iran-linked GPS spoofing affecting tanker navigation.',
  },
];
